"""remove_device_access_table

Revision ID: 9edb2bee08ac
Revises: 1635d497fbdc
Create Date: 2026-09-10 20:29:56.437416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9edb2bee08ac'
down_revision: Union[str, Sequence[str], None] = '1635d497fbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_access',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedded_system_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('access_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('granted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['embedded_system_id'], ['embedded_systems.id'], name=op.f('device_access_embedded_system_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('device_access_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('device_access_pkey'))
    )
    # ### end Alembic commands ###
